CREATE EXTENSION IF NOT EXISTIS "uuid-ossp";

CREATE TABLE IF NOT EXISTIS prices (
  id UUDI PRIMARY KEY,
  tittle TEXT NOT NULL,
  value DECIMAL NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);